#include<stdio.h>
int main()
{
    // TO INPUT AND OUT A STRING WITHOUT USING LOOP WE NEED HELP OF "gets()","puts()" function...... 
    char str[40];
   // scanf("%c",&str); use of & can be done for %d,%f,%c......
    //scanf("%s",str); 
    // When we use %s format specifier we don't need to write & ......
    // but this has a drawback, in this process scanf consider only the first word.....
    scanf("%[^\n]s",str);
    // or, gets(str);
    // insted of using %s we can consider %[^\n]s as format specifier.....
    puts(str);
    return 0;
}